#   To run the full stack:
#   docker compose --profile ai --profile frontend up
#
#   Frontend + backend
#   docker compose --profile frontend up
#
#   Backend only
#   docker compose up

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
     - backend
    networks:
      - taw
    profiles: [frontend]


  aiagent:
    build:
      context: ./AIagent
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - taw
    profiles: [ai]


  backend:
    build:
      context: ./backend/v3
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mydatabase
    depends_on:
      - mymongo
    networks:
      - taw

  mymongo:
    image: mongo:6
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - taw


networks:
  taw:
    name: taw
    driver: bridge
    external: true

volumes:
  mongodb-data:
