#
# Open this directory in VSC, click on the bottom left icon `><` and select "Reopen in Container".
#
# Official Node.js images in Docker Hub:
#  https://hub.docker.com/_/node

FROM node:25-trixie-slim
LABEL maintainer="Filippo Bergamasco <filippo.bergamasco@unive.it>"

WORKDIR /app
COPY . /app


