openapi: 3.0.0
info:
  title: Postmessages API
  version: 1.0.0
  description: A simple web application for the Web Technologies and Applications course.
paths:
  /api/v2/:
    get:
      summary: Get API Info
      description: Returns the version and a list of available endpoints.
      responses:
        '200':
          description: Successful response containing API version and available routes.
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string
                    example: 1.0.0
                  endpoints:
                    type: array
                    items:
                      type: string
                    example:
                      - GET /
                      - GET /messages
                      - POST /messages
                      - DELETE /messages?index=<n>
                      - GET /tags

  /api/v2/messages:
    get:
      summary: Retrieve all messages
      description: Returns all the posted messages.
      parameters:
        - name: tags
          in: query
          required: false
          description: filter messages by tag.
          schema:
            type: string
            example: tag1
        - name: skip
          in: query
          required: false
          description: number of messages to skip.
          schema:
            type: int
            example: 1
        - name: limit
          in: query
          required: false
          description: number of messages to return.
          schema:
            type: int
            example: 10
      responses:
        '200':
          description: A successful list of messages.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    content:
                      type: string
                      example: message text
                    tags:
                      type: array
                      items:
                        type: string
                      example:
                        - tag 1
                        - tag 2
                    timestamp:
                      type: date
                      example: 2026-04-26T19:27:39.836Z
    
    post:
      summary: Post a new message
      description: Post a new message to the server.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  example: This is a new message
                tags:
                  type: array
                  items:
                    type: string
                  example:
                    - tag1
                    - tag2
              required:
                - message
      responses:
        '200':
          description: ok.
          
    delete:
      summary: Delete a message
      description: Delete the n^th message from the list.
      parameters:
        - name: id
          in: query
          required: true
          description: The id of the message to delete.
          schema:
            type: string
            example: ABCDE
      responses:
        '200':
          description: Message successfully deleted.
        '400':
          description: Bad request (e.g., invalid index).
  /api/v2/tags:
    get:
      summary: Retrieve all tags
      description: Returns the list of all the existing tags.
      responses:
        '200':
          description: List of tags.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                  - tag 1
                  - tag 2
                  - tag 3